# Generated by Django 3.1.7 on 2021-04-27 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20210427_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquire',
            old_name='types',
            new_name='division',
        ),
    ]
