# Generated by Django 3.1.7 on 2021-04-29 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
