# Generated by Django 3.1.7 on 2021-04-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_delete_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquire',
            name='phone',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
