# Generated by Django 3.1.7 on 2021-12-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20211213_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='response',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
